# Generated by Django 2.0.3 on 2019-01-11 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('subtype', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('complement', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='ItemComplements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('dishcompl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('data', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.IntegerField(choices=[(1, 'edit'), (2, 'completed'), (3, 'paid'), (4, 'done')], default=1)),
                ('user', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(1, 'small'), (2, 'large')], default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('large', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PriceCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PriceCategories'),
        ),
        migrations.AddField(
            model_name='price',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Dish'),
        ),
        migrations.AddField(
            model_name='ordersitems',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Price'),
        ),
        migrations.AddField(
            model_name='itemcomplements',
            name='itemord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrdersItems'),
        ),
        migrations.AddField(
            model_name='itemcomplements',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Price'),
        ),
    ]
